(function () {
  var S = {
    'en-US': {
      name: 'English (US)', nativeName: 'English (US)', dir: 'ltr',
      s: {
        title: 'NEON DODGERS', score: 'Score', lives: 'Lives', best: 'Best', keys: 'Keys',
        totalXp: 'Total XP', musicTrack: 'Music Track', trackDimension: 'Dimension \u2013 Creo',
        trackSphere: 'Sphere \u2013 Creo', trackExoplanet: 'Exoplanet \u2013 Creo', trackField: 'Field of Hopes and Dreams \u2013 Deltarune', trackFallenDown: 'Fallen Down \u2013 Undertale', trackShop: 'The Shop \u2013 Undertale',         trackACybersWorld: "A CYBER'S WORLD? \u2013 Deltarune", trackTvWorld: 'TV World \u2013 Deltarune', trackMegalovania: 'Megalovania \u2013 Undertale', modeEndless: 'Endless', modeLevels: 'Levels',
        modeRace: 'Race', modeNinja: 'Ninja', selectDifficulty: 'Select Difficulty',
        modeSurvival: 'Survival Mode', modeChaos: 'Chaos Mode', modeSpeedRush: 'Speed Rush Mode',
        modeMeteor: 'Meteor Mode', modeReverse: 'Reverse Mode', modeZen: 'Zen Mode',
        modeBossRush: 'Boss Rush', modeSideScroll: 'Side-Scroll Mode', modeInverted: 'Inverted Mode',
        creatorBtn: 'Creator',
        startSurvival: 'Start Survival', startReverse: 'Start Reverse', startZen: 'Start Zen',
        startBossRush: 'Start Boss Rush',
        bossWave: 'Boss Wave {n}', bossDefeated: 'BOSS DEFEATED!',
        bossRushComplete: 'ALL BOSSES DOWN! Final score: {score}',
        bossRushDesc: 'Your blaster is always on. Face wave after wave of neon bosses \u2014 dodge their bullets and bring them down!',
        back: 'Back',
        survivalDesc: 'One life. No mercy. Speed never stops rising \u2014 how long can you last?',
        chaosDesc: 'Obstacles attack from every direction. Power-ups rain down constantly. Absolute madness!',
        speedRushDesc: '60 seconds on the clock. Score as many points as you can before time runs out!',
        meteorDesc: 'Meteors slam in from every edge. Watch for the warning markers \u2014 they show where impact is coming!',
        sideScrollDesc: 'Run through a side-scrolling gauntlet. Obstacles rush at you from the right \u2014 weave through the gaps and keep moving forward!',
        invertedDesc: 'Every few seconds your controls flip \u2014 up becomes down, right becomes left. Watch for the warning flash and rewire your brain mid-run!',
        reverseDesc: 'Your controls are flipped \u2014 right feels like left, up feels like down. Train your brain!',
        zenDesc: 'No lives, no game over. Obstacles can\u2019t hurt you \u2014 just drift, relax and collect coins.',
        speedRushDone: 'TIME\u2019S UP! Final score: {score}',
        selectLevel: 'Select Level', selectNinjaDifficulty: 'Select Ninja Difficulty',
        installApp: 'Add to Home Screen (optional)', howToPlay: 'How to Play',
        visitSite: 'Visit: {url}', iphoneTip: 'On iPhone: Share \u2192 Add to Home Screen',
        scrollForMore: '\u25BC Scroll for more',
        paused: 'PAUSED', resume: 'Resume', exitLevel: 'Exit',
        language: 'Language', retry: 'RETRY', mainMenu: 'MAIN MENU', gameOver: 'GAME OVER',
        suggestions: 'Suggestions and more',
        levelCleared: 'LEVEL CLEARED!', xpEarned: '+{xp} XP', timeRanOut: 'Time ran out!',
        slowMotion: 'SLOW MOTION!', blasterActive: 'BLASTER ACTIVE!', speedBoost: 'SPEED BOOST!',
        speedReduction: 'SPEED REDUCTION!', raceTabCpu: 'vs CPU', raceTabOnline: 'Online',
        racePlayerName: 'Your name', racePlayerNamePlaceholder: 'Player', racePlayerCount: 'Players (2\u20135)',
        racePlayerCountOption: '{n} players', raceDifficulty: 'Difficulty',
        raceStartCpu: 'Start Race vs CPU', raceServerUrl: 'Server URL (optional)',
        raceCreateRoom: 'Create Room', raceJoinCode: 'Join with code',
        raceJoinRoom: 'Join Room', raceBack: 'Back', raceLobby: 'Race Lobby',
        raceShareCode: 'Share this code:', raceReady: 'Ready', raceStart: 'Start Race',
        raceLeave: 'Leave', raceWaiting: 'Waiting for players ({n}/{max})',
        raceRoomFull: 'Room full \u2014 ready up!', raceStandings: 'Standings',
        raceEliminated: 'ELIMINATED!', raceWatchStandings: 'Watch the standings \u2014 last survivor wins',
        raceOver: 'RACE OVER', youWin: 'YOU WIN!', wins: '{name} WINS!',
        raceAgain: 'Race Again', raceMainMenu: 'Main Menu', raceSurvived: 'Survived',
        raceEliminatedStatus: 'Eliminated', raceOut: 'OUT', racePts: 'pts', raceYou: '(you)',
        unlockForXp: 'Unlock {name} for {cost} XP?', notEnoughXp: 'Not enough XP!',
        shopBuy: 'Buy', shopEquip: 'Equip', shopEquipped: 'Equipped', shopFree: 'FREE', shopBtn: 'Shop', shopClose: 'Close', shopTitle: 'SKIN SHOP', shopSub: 'Customize your look with XP',
        shopCost: '{cost} XP',
        skinDefault: 'Default Neon', skinForest: 'Forest Nature', skinLava: 'Lava',
        skinOcean: 'Deep Ocean', skinMidnight: 'Midnight', skinGold: 'Royal Gold', skinCandy: 'Candy Pop',
        unlockAll: 'Unlock All Levels ({cost} XP)', gameOverScore: 'Score: {score}',
        tutTitle: '\uD83D\uDCD6 HOW TO PLAY',
        tutBasicsTitle: '\uD83C\uDFAE Basics (All Modes)',
        tutBasics1: '<b>Mouse / Finger:</b> Move your cursor or drag to control your position on screen.',
        tutBasics2: '<b>Keyboard:</b> Arrow keys or WASD also move your neon square.',
        tutBasics3: '<b>Coins</b> (yellow circles) give you +1 Life when collected.',
        tutBasics4: '<b>Keys</b> (orange) unlock White Wall obstacles \u2014 use a key to slice through them safely.',
        tutBasics5: '<b>Power-ups:</b> Green = Slow Motion, Red = Blaster (auto fires bullets).',
        tutBasics6: '<b>Portals</b> change your speed temporarily \u2014 cyan slows down, magenta speeds up.',
        tutEndlessTitle: '\u267E\uFE0F Endless Mode',
        tutEndless1: 'Dodge <b>pink obstacles</b> falling and flying across the screen.',
        tutEndless2: 'Your <b>Score</b> increases every time you survive and dodge. Obstacles get faster over time!',
        tutEndless3: 'Your <b>Best Score</b> is saved and shown in the top-right corner.',
        tutEndless4: 'You start with <b>1 Life</b>. Hit an obstacle and it\u2019s Game Over \u2014 unless you collected a coin!',
        tutEndless5: 'Choose difficulty from <b>Beginner \u2192 God</b>. Higher = faster obstacles, more at once.',
        tutLevelsTitle: '\uD83C\uDFC5 Levels Mode',
        tutLevels1: 'Survive a <b>countdown timer</b> to clear the level. The timer is shown where the score usually is.',
        tutLevels2: 'Clear a level to earn <b>XP</b>: 1 XP for Level 1, 2 for Level 2... up to 10 XP for Level 10.',
        tutLevels3: 'Levels are <b>locked</b> by default. Beat a level to unlock the next one automatically.',
        tutLevels4: 'Spend <b>30 XP</b> to skip a locked level, or <b>70 XP</b> to unlock all levels at once!',
        tutLevels5: 'Survive until the timer hits 0 and you win the level \u2014 a victory explosion fires off!',
        tutNinjaTitle: '\uD83E\uDD77 Ninja Mode',
        tutNinja1: '<b>Click &amp; drag</b> (or swipe on mobile) to draw your glowing green blade across the screen.',
        tutNinja2: '<b>Cyan obstacles</b> are fruits \u2014 slice them for +1 Score!',
        tutNinja3: '<b>Pink obstacles</b> are Bombs \u2014 slicing them costs you 1 Life. At 1 Life = instant Game Over!',
        tutNinja4: 'If a cyan fruit <b>falls off screen</b> without being sliced, you lose 1 Life.',
        tutNinja5: 'Slice <b>Coins</b> to collect them (+1 Life). Slice <b>Keys</b> to collect them too!',
        tutNinja6: 'Slice a <b>White Wall</b> with a Key = +1 Score. Without a key = lose 1 Life.',
        tutNinja7: 'You start with <b>3 Lives</b> in Ninja Mode \u2014 build them up by collecting coins!',
        tutRaceTitle: '\uD83C\uDFC1 Race Mode',
        tutRace1: '<b>vs CPU:</b> Pick your difficulty and race against AI bots. Last one dodging wins!',
        tutRace2: '<b>Online:</b> Create or join a room with a 4-letter code and race against real players!',
        tutRace3: 'When you get hit, you\u2019re <b>Eliminated</b> \u2014 but you can still watch the live standings.',
        tutRace4: 'The last surviving player is declared the <b>winner</b>!',
        tutTipsTitle: '\uD83D\uDCA1 Tips &amp; Tricks',
        tutTips1: 'Always move to the <b>edges</b> of the screen \u2014 obstacles are densest in the center.',
        tutTips2: 'In Ninja Mode, make <b>long diagonal swipes</b> to hit multiple fruits at once.',
        tutTips3: 'Grab <b>coins early</b> in Endless \u2014 the extra life is a huge safety net later.',
        tutTips4: 'Save your <b>XP</b> to unlock high levels directly if you find Beginner too easy.',
        tutTips5: 'Slow Motion power-ups let you breathe \u2014 use them to collect coins safely.',
        tutTips6: 'On iPhone: tap <b>Share \u2192 Add to Home Screen</b> to play offline like a real app!',
        tutTips7: 'Share the link <b>neon-dodgers.vercel.app</b> with friends to race online!',
        tutSurvivalTitle: '\u2764\uFE0F\u200D\uD83D\uDD25 Survival Mode',
        tutSurvival1: 'You have exactly <b>1 Life</b>. One hit and it\u2019s over \u2014 no extra lives, no mercy.',
        tutSurvival2: 'The speed <b>ramps up continuously</b> \u2014 obstacles never stop getting faster and denser.',
        tutSurvival3: 'Your score is a <b>stopwatch</b> \u2014 every frame you survive is a point. Beat your best time!',
        tutSurvival4: '<b>Tip:</b> Small, controlled movements beat frantic ones. Staying calm at the edges keeps you alive longest.',
        tutChaosTitle: '\uD83C\uDF0A\uFE0F Chaos Mode',
        tutChaos1: 'Obstacles fall <b>from every direction</b> \u2014 top, bottom, left and right. Watch your whole screen!',
        tutChaos2: '<b>Power-ups spawn far more often</b> \u2014 grab Slow Motion or Blaster whenever you can.',
        tutChaos3: 'You start with <b>3 Lives</b>. Coins still give +1 Life each.',
        tutChaos4: '<b>Tip:</b> In Chaos, the center is a trap. Camp in a corner and react only when something comes your way.',
        tutSpeedRushTitle: '\u26A1 Speed Rush Mode',
        tutSpeedRush1: 'You have <b>60 seconds</b> \u2014 the countdown timer shows where your score usually is.',
        tutSpeedRush2: '<b>Coins are your lifeline</b>: each one adds +1 Life AND +1 point. Grab them all!',
        tutSpeedRush3: 'When time runs out your <b>final score is saved</b> as your best. Beat it next run!',
        tutSpeedRush4: '<b>Tip:</b> Stay alive for the full 60s. Dying early wastes the run \u2014 prioritize dodging over coin hunting.',
        tutMeteorTitle: '\u2604\uFE0F Meteor Mode',
        tutMeteor1: 'A <b>flashing red warning marker</b> appears before a meteor lands \u2014 it shows exactly where impact will happen.',
        tutMeteor2: 'Meteors <b>strike from every edge</b> of the screen, not just the top. Don\u2019t hug the walls!',
        tutMeteor3: 'After the warning, the meteor <b>slams down and explodes</b> into fragments. Avoid the impact zone.',
        tutMeteor4: '<b>Tip:</b> Watch the warnings, not the meteors. As soon as a marker flashes, move away from it.',
        tutReverseTitle: '\uD83D\uDD04 Reverse Mode',
        tutReverse1: 'Your controls are <b>inverted</b> \u2014 ArrowRight moves you LEFT, ArrowUp moves you DOWN. Mouse/finger is flipped too!',
        tutReverse2: 'Classic Endless obstacles, but your <b>brain has to work backwards</b> to dodge them.',
        tutReverse3: '<b>Tip:</b> Go slow at first. Move in the "wrong" direction on purpose until the flip becomes muscle memory.',
        tutZenTitle: '\uD83E\uDDD8\u200D\u2642\uFE0F Zen Mode',
        tutZen1: '<b>You can\u2019t die.</b> Obstacles pass right through you \u2014 no lives, no game over, no stress.',
        tutZen2: 'Chase <b>coins</b> \u2014 each one is +1 point. Your goal is a pure, relaxing high score.',
        tutZen3: 'Just drift through the neon. It\u2019s the perfect mode to <b>chill out</b> and test the skin shop.',
        tutZen4: '<b>Tip:</b> No rush! Plan lazy paths through coin lines and watch the obstacles flow by.',
        tutClose: '\u2705 Got it!', raceLastStanding: 'Last one standing wins!',
        achievementsBtn: 'Achievements', achievementsTitle: 'ACHIEVEMENTS',
        achievementsClose: 'Close', achievementUnlocked: 'Achievement unlocked!',
        achievementsUnlocked: 'Unlocked {n}/{total}', achievementsLocked: 'Locked',
        achFirstRunName: 'First Steps', achFirstRunDesc: 'Play your first game.',
        achScore100Name: 'Century', achScore100Desc: 'Reach a score of 100.',
        achScore500Name: 'On Fire', achScore500Desc: 'Reach a score of 500.',
        achScore1000Name: 'Neon Legend', achScore1000Desc: 'Reach a score of 1000.',
        achCoins50Name: 'Coin Collector', achCoins50Desc: 'Collect 50 coins in total.',
        achCoins200Name: 'Coin Hoarder', achCoins200Desc: 'Collect 200 coins in total.',
        achSurvivor60Name: 'Marathon', achSurvivor60Desc: 'Survive 60 seconds in Survival Mode.',
        achLevel5Name: 'Level Climber', achLevel5Desc: 'Clear 5 levels.',
        achSpeedy100Name: 'Speed Demon', achSpeedy100Desc: 'Score 100 in a Speed Rush run.',
        achBossSlayerName: 'Boss Slayer', achBossSlayerDesc: 'Defeat your first boss.',
        achBossMasterName: 'Boss Master', achBossMasterDesc: 'Clear all 5 waves of Boss Rush.',
        achChaos50Name: 'Chaos Runner', achChaos50Desc: 'Reach a score of 50 in Chaos Mode.',
        tutBossRushTitle: '\uD83D\uDCA5 Boss Rush Mode',
        tutBossRush1: 'Your <b>blaster is always active</b> \u2014 you auto-fire at the boss every few frames. No power-up needed!',
        tutBossRush2: 'The boss has an <b>HP bar</b> at the top. Shoot it to chip away its health and end the wave.',
        tutBossRush3: 'Bosses fire <b>aimed shots, radial sprays and dash attacks</b>. Dodge the magenta bullets \u2014 each hit costs 1 Life.',
        tutBossRush4: 'You start with <b>3 Lives</b>. Survive all 5 waves of bosses to clear the mode!',
        tutCreatorTitle: '\uD83C\uDFA8 Creator',
        tutCreator1: 'Tap the <b>\uD83C\uDFA8 Creator</b> button on the main menu to build your own levels \u2014 place Blocks, Spikes, Coins, Keys, Portals, Gates, Power-ups, Speed pads and Invert zones on a grid.',
        tutCreator2: 'Pick <b>Vertical</b> or <b>Side</b> scrolling, set the speed and size, and choose a song to match the vibe of your level.',
        tutCreator3: 'Hit <b>Playtest</b> to try your level instantly. Press <b>Esc</b> to stop and jump right back into the editor.',
        tutCreator4: '<b>Save</b> keeps your level on this device. <b>Upload</b> shares it so other players can race through your creation!',
        raceModeTitle: 'RACE MODE', raceLobbyStatusReady: 'Ready!',
        raceLobbyStatusWaiting: 'Waiting\u2026', levelLocked: 'Locked',
        diffBeginner: 'Beginner', diffEasy: 'Easy', diffNormal: 'Normal', diffHard: 'Hard',
        diffExpert: 'Expert', diffMaster: 'Master', diffWizard: 'Wizard', diffInsane: 'Insane',
        diffLegend: 'Legend', diffGod: 'God', raceWins: 'WINS',
        racer1: 'NeonBot', racer2: 'CyberAce', racer3: 'PixelRush', racer4: 'Glitch',
        racer5: 'Vortex', racer6: 'StarDodge', racer7: 'Pulse',
        scoreDisplay: 'Score: {score}', livesDisplay: 'Lives: {n}', keysDisplay: 'Keys: {n}',
        bestDisplay: 'Best: {score}', xpDisplay: 'Total XP: {xp}',
        timeDisplay: 'Time: {s}s', levelClearedTitle: 'LEVEL CLEARED!',
        levelFailed: 'Time ran out!', timeRanOut: 'Time ran out!',
        unlockAllConfirm: 'Unlock ALL remaining levels for {cost} XP?',
        disconnected: 'Disconnected from server',
        deployServer: 'Deploy the free server in the server/ folder, or play vs CPU offline.',
        enterRoomCode: 'Enter a 4-character room code',
        yes: 'Yes', no: 'No', confirm: 'Confirm', cancel: 'Cancel'
      }
    },
    'en-GB': {
      name: 'English (UK)', nativeName: 'English (UK)', dir: 'ltr',
      s: {
        title: 'NEON DODGERS', score: 'Score', lives: 'Lives', best: 'Best', keys: 'Keys',
        totalXp: 'Total XP', musicTrack: 'Music Track',
        howToPlay: 'How to Play', language: 'Language', retry: 'RETRY', mainMenu: 'MAIN MENU',
        gameOver: 'GAME OVER', levelCleared: 'LEVEL CLEARED!', youWin: 'YOU WIN!',
        raceOver: 'RACE OVER', raceAgain: 'Race Again', raceMainMenu: 'Main Menu',
        tutTips1: 'Always move to the edges of the screen \u2014 obstacles are densest in the centre.',
        diffBeginner: 'Beginner', diffEasy: 'Easy', diffNormal: 'Normal', diffHard: 'Hard',
        diffExpert: 'Expert', diffMaster: 'Master', diffWizard: 'Wizard', diffInsane: 'Insane',
        diffLegend: 'Legend', diffGod: 'God', raceReady: 'Ready', raceLeave: 'Leave',
        raceBack: 'Back', tutClose: 'Got it!',
        selectDifficulty: 'Select Difficulty', selectLevel: 'Select Level',
        installApp: 'Add to Home Screen (optional)',
        slowMotion: 'SLOW MOTION!', blasterActive: 'BLASTER ACTIVE!',
        speedBoost: 'SPEED BOOST!', speedReduction: 'SPEED REDUCTION!',
        raceTabCpu: 'vs CPU', raceTabOnline: 'Online',
        racePlayerName: 'Your name', racePlayerCount: 'Players (2\u20135)',
        raceDifficulty: 'Difficulty', raceStartCpu: 'Start Race vs CPU',
        raceCreateRoom: 'Create Room', raceJoinRoom: 'Join Room',
        raceLobby: 'Race Lobby', raceShareCode: 'Share this code:',
        raceStart: 'Start Race', raceStandings: 'Standings',
        raceEliminated: 'ELIMINATED!', raceSurvived: 'Survived',
        raceEliminatedStatus: 'Eliminated', raceOut: 'OUT', racePts: 'pts', raceYou: '(you)',
        tutTitle: 'HOW TO PLAY', tutBasicsTitle: 'Basics (All Modes)',
        tutEndlessTitle: 'Endless Mode', tutLevelsTitle: 'Levels Mode',
        tutNinjaTitle: 'Ninja Mode', tutRaceTitle: 'Race Mode', tutTipsTitle: 'Tips & Tricks',
        racer1: 'NeonBot', racer2: 'CyberAce', racer3: 'PixelRush', racer4: 'Glitch',
        racer5: 'Vortex', racer6: 'StarDodge', racer7: 'Pulse',
        scoreDisplay: 'Score: {score}', livesDisplay: 'Lives: {n}', keysDisplay: 'Keys: {n}',
        bestDisplay: 'Best: {score}', xpDisplay: 'Total XP: {xp}',
        timeDisplay: 'Time: {s}s', gameOverScore: 'Score: {score}',
        unlockForXp: 'Unlock {name} for {cost} XP?', notEnoughXp: 'Not enough XP!',
        unlockAll: 'Unlock All Levels ({cost} XP)', xpEarned: '+{xp} XP',
        raceModeTitle: 'RACE MODE', raceLastStanding: 'Last one standing wins!',
        unlockAll: 'Unlock All Levels ({cost} XP)',
        disconnected: 'Disconnected from server',
      }
    },
    'en-AU': {
      name: 'English (Australia)', nativeName: 'English (Australia)', dir: 'ltr',
      s: {
        title: 'NEON DODGERS', score: 'Score', lives: 'Lives', best: 'Best', keys: 'Keys',
        totalXp: 'Total XP', howToPlay: 'How to Play', language: 'Language',
        retry: 'RETRY', mainMenu: 'MAIN MENU', gameOver: 'GAME OVER', youWin: 'YOU WIN!',
        raceOver: 'RACE OVER', diffBeginner: 'Beginner', diffEasy: 'Easy',
        diffNormal: 'Normal', diffHard: 'Hard', raceReady: 'Ready', raceLeave: 'Leave',
        raceAgain: 'Race Again', raceMainMenu: 'Main Menu', tutClose: 'Got it!',
        tutTips1: 'Always move to the edges of the screen \u2014 obstacles are densest in the centre.',
        scoreDisplay: 'Score: {score}', livesDisplay: 'Lives: {n}', keysDisplay: 'Keys: {n}',
        bestDisplay: 'Best: {score}', xpDisplay: 'Total XP: {xp}',
        gameOverScore: 'Score: {score}'
      }
    },
    'en-CA': {
      name: 'English (Canada)', nativeName: 'English (Canada)', dir: 'ltr',
      s: {
        title: 'NEON DODGERS', score: 'Score', lives: 'Lives', best: 'Best', keys: 'Keys',
        totalXp: 'Total XP', howToPlay: 'How to Play', language: 'Language',
        retry: 'RETRY', mainMenu: 'MAIN MENU', gameOver: 'GAME OVER', youWin: 'YOU WIN!',
        raceOver: 'RACE OVER', diffBeginner: 'Beginner', diffEasy: 'Easy',
        diffNormal: 'Normal', raceReady: 'Ready', raceAgain: 'Race Again',
        raceMainMenu: 'Main Menu', tutClose: 'Got it!',
        scoreDisplay: 'Score: {score}', livesDisplay: 'Lives: {n}', keysDisplay: 'Keys: {n}',
        bestDisplay: 'Best: {score}', xpDisplay: 'Total XP: {xp}',
        gameOverScore: 'Score: {score}'
      }
    },
    'en-IN': {
      name: 'English (India)', nativeName: 'English (India)', dir: 'ltr',
      s: {
        title: 'NEON DODGERS', score: 'Score', lives: 'Lives', best: 'Best', keys: 'Keys',
        totalXp: 'Total XP', howToPlay: 'How to Play', language: 'Language',
        retry: 'RETRY', mainMenu: 'MAIN MENU', gameOver: 'GAME OVER', youWin: 'YOU WIN!',
        raceOver: 'RACE OVER', diffBeginner: 'Beginner', diffEasy: 'Easy',
        diffNormal: 'Normal', raceReady: 'Ready', tutClose: 'Got it!',
        scoreDisplay: 'Score: {score}', livesDisplay: 'Lives: {n}', keysDisplay: 'Keys: {n}',
        bestDisplay: 'Best: {score}', xpDisplay: 'Total XP: {xp}',
        gameOverScore: 'Score: {score}'
      }
    }
  };
  for (var k in S) { if (S.hasOwnProperty(k)) NeonI18n.addLang(k, S[k]); }
})();
