(function () {
  var S = {
    'fr-FR': {
      name: 'French (France)', nativeName: 'Fran\u00e7ais (France)', dir: 'ltr',
      s: {
        title: 'NEON DODGERS', score: 'Score', lives: 'Vies', best: 'Meilleur', keys: 'Cl\u00e9s',
        totalXp: 'XP Total', musicTrack: 'Piste musicale', trackDimension: 'Dimension \u2013 Creo',
        trackSphere: 'Sphere \u2013 Creo', trackExoplanet: 'Exoplanet \u2013 Creo', trackField: 'Field of Hopes and Dreams \u2013 Deltarune', trackFallenDown: 'Fallen Down \u2013 Undertale', trackShop: 'The Shop \u2013 Undertale',         trackACybersWorld: "A CYBER'S WORLD? \u2013 Deltarune", trackTvWorld: 'TV World \u2013 Deltarune', trackMegalovania: 'Megalovania \u2013 Undertale', modeEndless: 'Infini', modeLevels: 'Niveaux',
        modeRace: 'Course', modeNinja: 'Ninja',
        modeSurvival: 'Mode Survie', modeChaos: 'Mode Chaos', modeSpeedRush: 'Mode Course de Vitesse',
        modeMeteor: 'Mode M\u00e9t\u00e9ore', modeReverse: 'Mode Inverse', modeZen: 'Mode Zen',
        modeBossRush: 'Boss Rush',
        modeSideScroll: 'Mode D\u00e9filement Lat\u00e9ral', modeInverted: 'Mode Invers\u00e9',
        creatorBtn: 'Cr\u00e9ateur',
        sideScrollDesc: 'Esquivez des obstacles lat\u00e9raux \u2014 d\u00e9placez-vous pour survivre \u00e0 cette course effr\u00e9n\u00e9e !',
        invertedDesc: 'Les contr\u00f4les s\u2019inversent chaque 7 secondes \u2014 restez vif et pr\u00e9voyant !',
        startSurvival: 'D\u00e9marrer Survie', startReverse: 'D\u00e9marrer Inverse', startZen: 'D\u00e9marrer Zen',
        startBossRush: 'D\u00e9marrer Boss Rush',
        bossWave: 'Vague de boss {n}', bossDefeated: 'BOSS VAINCU !',
        bossRushComplete: 'TOUS LES BOSS VAINCUS ! Score final : {score}',
        bossRushDesc: 'Votre blaster est toujours actif. Affrontez vague apr\u00e8s vague des boss n\u00e9on \u2014 esquivez leurs balles et abattez-les !',
        achievementsBtn: 'Succ\u00e8s', achievementsTitle: 'SUCC\u00c8S',
        achievementsClose: 'Fermer', achievementUnlocked: 'Succ\u00e8s d\u00e9bloqu\u00e9 !',
        achievementsUnlocked: 'D\u00e9bloqu\u00e9s {n}/{total}', achievementsLocked: 'Verrouill\u00e9',
        achFirstRunName: 'Premiers pas', achFirstRunDesc: 'Jouez \u00e0 votre premi\u00e8re partie.',
        achScore100Name: 'Cent', achScore100Desc: 'Atteignez un score de 100.',
        achScore500Name: 'En feu', achScore500Desc: 'Atteignez un score de 500.',
        achScore1000Name: 'L\u00e9gende n\u00e9on', achScore1000Desc: 'Atteignez un score de 1000.',
        achCoins50Name: 'Collectionneur', achCoins50Desc: 'Collectez 50 pi\u00e8ces au total.',
        achCoins200Name: 'Amasseur', achCoins200Desc: 'Collectez 200 pi\u00e8ces au total.',
        achSurvivor60Name: 'Marathon', achSurvivor60Desc: 'Survivez 60 secondes en mode Survie.',
        achLevel5Name: 'Grimpeur', achLevel5Desc: 'R\u00e9ussissez 5 niveaux.',
        achSpeedy100Name: 'D\u00e9mon de vitesse', achSpeedy100Desc: 'Marquez 100 en course de vitesse.',
        achBossSlayerName: 'Tueur de boss', achBossSlayerDesc: 'Vainquez votre premier boss.',
        achBossMasterName: 'Ma\u00eetre des boss', achBossMasterDesc: 'Terminez les 5 vagues du mode Boss Rush.',
        achChaos50Name: 'Coureur du chaos', achChaos50Desc: 'Atteignez un score de 50 en mode Chaos.',
        tutBossRushTitle: '\uD83D\uDCA5 Mode Boss Rush',
        tutBossRush1: 'Votre <b>blaster est toujours actif</b> \u2014 vous tirez automatiquement sur le boss toutes les quelques images. Pas besoin de power-up !',
        tutBossRush2: 'Le boss a une <b>barre de vie</b> en haut. Tirez pour r\u00e9duire sa sant\u00e9 et terminer la vague.',
        tutBossRush3: 'Les boss lancent des <b>tirs vis\u00e9s, des rafales radiales et des attaques en d\u00e9placement</b>. Esquivez les balles magenta \u2014 chaque coup co\u00fbte 1 Vie.',
        tutBossRush4: 'Vous commencez avec <b>3 Vies</b>. Survivez aux 5 vagues de boss pour terminer le mode !',
        tutCreatorTitle: '\uD83C\uDFA8 Cr\u00e9ateur',
        tutCreator1: 'Appuyez sur le bouton <b>\uD83C\uDFA8 Cr\u00e9ateur</b> du menu principal pour cr\u00e9er vos propres niveaux \u2014 placez des blocs, pics, pi\u00e8ces, cl\u00e9s, portails, barri\u00e8res, power-ups, tapis de vitesse et zones d\u2019inversion sur une grille.',
        tutCreator2: 'Choisissez un d\u00e9filement <b>Vertical</b> ou <b>Lat\u00e9ral</b>, r\u00e9glez la vitesse et la taille, puis choisissez une musique adapt\u00e9e \u00e0 votre niveau.',
        tutCreator3: 'Cliquez sur <b>Playtest</b> pour tester votre niveau instantan\u00e9ment. Appuyez sur <b>\u00c9chap</b> pour revenir dans l\u2019\u00e9diteur.',
        tutCreator4: '<b>Enregistrer</b> garde votre niveau sur cet appareil. <b>Publier</b> le partage afin que d\u2019autres joueurs puissent s\u2019y affronter !',
        back: 'Retour',
        survivalDesc: 'Une seule vie. Pas de piti\u00e9. La vitesse augmente sans cesse \u2014 combien de temps tiendrez-vous ?',
        chaosDesc: 'Les obstacles attaquent de toutes les directions. Les power-ups pleuvent constamment. Folie totale !',
        speedRushDesc: '60 secondes au chrono. Marquez un maximum de points avant la fin du temps !',
        meteorDesc: 'Les m\u00e9t\u00e9ores s\u2019abattent de partout. Surveillez les marqueurs d\u2019avertissement \u2014 ils montrent o\u00f9 \u00e7a va tomber !',
        reverseDesc: 'Vos commandes sont invers\u00e9es \u2014 droite = gauche, haut = bas. Entra\u00eenez votre cerveau !',
        zenDesc: 'Pas de vies, pas de game over. Les obstacles ne peuvent pas vous blesser \u2014 flottez, d\u00e9tendez-vous et ramassez des pi\u00e8ces.',
        speedRushDone: 'TEMPS \u00c9COUL\u00c9 ! Score final : {score}',
        diffBeginner: 'D\u00e9butant', diffEasy: 'Facile', diffNormal: 'Normal', diffHard: 'Difficile',
        diffExpert: 'Expert', diffMaster: 'Ma\u00eetre', diffWizard: 'Sorcier', diffInsane: 'D\u00e9ment',
        diffLegend: 'L\u00e9gende', diffGod: 'Dieu',
        selectDifficulty: 'Choisir la difficult\u00e9', selectLevel: 'Choisir le niveau',
        selectNinjaDifficulty: 'Choisir la difficult\u00e9 Ninja',
        installApp: 'Ajouter \u00e0 l\u2019\u00e9cran d\u2019accueil (optionnel)',
        howToPlay: 'Comment jouer', language: 'Langue',
        scrollForMore: '\u25BC Faites d\u00e9filer',
        paused: 'PAUSE', resume: 'Reprendre', exitLevel: 'Quitter',
        retry: 'R\u00c9ESSAYER', mainMenu: 'MENU PRINCIPAL', gameOver: 'FIN DE PARTIE',
        suggestions: 'Suggestions et plus',
        levelCleared: 'NIVEAU R\u00c9USSI !', xpEarned: '+{xp} XP', timeRanOut: 'Temps \u00e9coul\u00e9 !',
        slowMotion: 'RALENTI !', blasterActive: 'BLASTER ACTIF !', speedBoost: 'ACC\u00c9L\u00c9RATION !',
        speedReduction: 'RALENTISSEMENT !', raceTabCpu: 'contre CPU', raceTabOnline: 'En ligne',
        racePlayerName: 'Votre nom', racePlayerNamePlaceholder: 'Joueur', racePlayerCount: 'Joueurs (2\u20135)',
        racePlayerCountOption: '{n} joueurs', raceDifficulty: 'Difficult\u00e9', raceStartCpu: 'Lancer la course contre CPU',
        raceServerUrl: 'URL du serveur (optionnel)',
        raceCreateRoom: 'Cr\u00e9er une salle', raceJoinCode: 'Rejoindre avec un code',
        raceJoinRoom: 'Rejoindre une salle', raceBack: 'Retour',
        raceLobby: 'Hall d\u2019attente', raceShareCode: 'Partagez ce code :',
        raceReady: 'Pr\u00eat', raceStart: 'Commencer la course', raceLeave: 'Quitter',
        raceStandings: 'Classement', raceEliminated: '\u00c9LIMIN\u00c9 !',
        raceWatchStandings: 'Regardez le classement \u2014 le dernier survivant gagne',
        raceOver: 'COURSE TERMIN\u00c9E', youWin: 'VOUS AVEZ GAGN\u00c9 !',
        wins: '{name} GAGNE !', raceAgain: 'Refaire une course', raceMainMenu: 'Menu principal',
        raceSurvived: 'A surv\u00e9cu', raceEliminatedStatus: '\u00c9limin\u00e9',
        raceOut: 'OUT', racePts: 'pts', raceYou: '(vous)',
        raceWaiting: 'Attente des joueurs ({n}/{max})',
        raceRoomFull: 'Salle pleine \u2014 pr\u00eat !',
        unlockForXp: 'D\u00e9bloquer {name} pour {cost} XP ?', notEnoughXp: 'Pas assez d\u2019XP !',
        shopBuy: 'Acheter', shopEquip: '\u00c9quiper', shopEquipped: '\u00c9quip\u00e9', shopFree: 'GRATUIT', shopBtn: 'Boutique', shopClose: 'Fermer', shopTitle: 'BOUTIQUE DE SKINS', shopSub: 'Personnalisez votre look avec XP',
        shopCost: '{cost} XP',
        skinDefault: 'Neon par d\u00e9faut', skinForest: 'Nature foresti\u00e8re', skinLava: 'Lave',
        skinOcean: 'Oc\u00e9an profond', skinMidnight: 'Minuit', skinGold: 'Or royal', skinCandy: 'Bonbon Pop',
        unlockAll: 'D\u00e9bloquer tous les niveaux ({cost} XP)',
        gameOverScore: 'Score : {score}',
        scoreDisplay: 'Score\u00a0: {score}', livesDisplay: 'Vies\u00a0: {n}',
        keysDisplay: 'Cl\u00e9s\u00a0: {n}', bestDisplay: 'Meilleur\u00a0: {score}',
        xpDisplay: 'XP Total\u00a0: {xp}', timeDisplay: 'Temps\u00a0: {s}s',
        tutTitle: '\uD83D\uDCD6 COMMENT JOUER', tutBasicsTitle: '\uD83C\uDFAE Bases (tous les modes)',
        tutBasics1: '<b>Souris / Doigt :</b> d\u00e9placez votre curseur ou faites glisser pour contr\u00f4ler votre position \u00e0 l\u2019\u00e9cran.',
        tutBasics2: '<b>Clavier :</b> les fl\u00e8ches ou WASD d\u00e9placent aussi votre carr\u00e9 n\u00e9on.',
        tutBasics3: '<b>Les pi\u00e8ces</b> (cercles jaunes) vous donnent +1 Vie quand vous les collectez.',
        tutBasics4: '<b>Les Cl\u00e9s</b> (orange) d\u00e9verrouillent les obstacles Mur Blanc \u2014 utilisez une cl\u00e9 pour les trancher sans danger.',
        tutBasics5: '<b>Power-ups :</b> Vert = Ralenti, Rouge = Blaster (tire des projectiles automatiquement).',
        tutBasics6: '<b>Les portails</b> changent temporairement votre vitesse \u2014 le cyan ralentit, le magenta acc\u00e9l\u00e8re.',
        tutEndlessTitle: '\u267E\uFE0F Mode Infini',
        tutEndless1: 'Esquivez les <b>obstacles roses</b> qui tombent et volent \u00e0 travers l\u2019\u00e9cran.',
        tutEndless2: 'Votre <b>Score</b> augmente chaque fois que vous survivez et esquivez. Les obstacles acc\u00e9l\u00e8rent avec le temps !',
        tutEndless3: 'Votre <b>Meilleur Score</b> est sauvegard\u00e9 et affich\u00e9 en haut \u00e0 droite.',
        tutEndless4: 'Vous commencez avec <b>1 Vie</b>. Touchez un obstacle et c\u2019est Game Over \u2014 sauf si vous avez collect\u00e9 une pi\u00e8ce !',
        tutEndless5: 'Choisissez la difficult\u00e9 de <b>D\u00e9butant \u2192 Dieu</b>. Plus haut = obstacles plus rapides et plus nombreux.',
        tutLevelsTitle: '\uD83C\uDFC5 Mode Niveaux',
        tutLevels1: 'Survivez au <b>compte \u00e0 rebours</b> pour r\u00e9ussir le niveau. Le minuteur s\u2019affiche \u00e0 la place du score habituel.',
        tutLevels2: 'R\u00e9ussir un niveau rapporte de l\u2019<b>XP</b> : 1 XP pour le niveau 1, 2 pour le niveau 2... jusqu\u2019\u00e0 10 XP pour le niveau 10.',
        tutLevels3: 'Les niveaux sont <b>verrouill\u00e9s</b> par d\u00e9faut. Battez un niveau pour d\u00e9bloquer automatiquement le suivant.',
        tutLevels4: 'D\u00e9pensez <b>30 XP</b> pour passer un niveau verrouill\u00e9, ou <b>70 XP</b> pour tout d\u00e9bloquer d\u2019un coup !',
        tutLevels5: 'Survivez jusqu\u2019\u00e0 ce que le minuteur atteigne 0 et vous gagnez le niveau \u2014 une explosion de victoire part !',
        tutNinjaTitle: '\uD83E\uDD77 Mode Ninja',
        tutNinja1: '<b>Cliquez et glissez</b> (ou balayez sur mobile) pour dessiner votre lame verte lumineuse sur l\u2019\u00e9cran.',
        tutNinja2: '<b>Les obstacles cyan</b> sont des fruits \u2014 tranchez-les pour +1 Score !',
        tutNinja3: '<b>Les obstacles roses</b> sont des Bombes \u2014 les trancher vous co\u00fbte 1 Vie. \u00c0 1 Vie = Game Over imm\u00e9diat !',
        tutNinja4: 'Si un fruit cyan <b>tombe hors de l\u2019\u00e9cran</b> sans \u00eatre tranch\u00e9, vous perdez 1 Vie.',
        tutNinja5: 'Tranchez les <b>Pi\u00e8ces</b> pour les collecter (+1 Vie). Tranchez aussi les <b>Cl\u00e9s</b> !',
        tutNinja6: 'Trancher un <b>Mur Blanc</b> avec une Cl\u00e9 = +1 Score. Sans cl\u00e9 = perdre 1 Vie.',
        tutNinja7: 'Vous commencez avec <b>3 Vies</b> en mode Ninja \u2014 augmentez-les en collectant des pi\u00e8ces !',
        tutRaceTitle: '\uD83C\uDFC1 Mode Course',
        tutRace1: '<b>vs CPU :</b> choisissez votre difficult\u00e9 et affrontez des IA. Le dernier survivant gagne !',
        tutRace2: '<b>En ligne :</b> cr\u00e9ez ou rejoignez une salle avec un code \u00e0 4 lettres et courez contre de vrais joueurs !',
        tutRace3: 'Quand vous \u00eates touch\u00e9, vous \u00eates <b>\u00c9limin\u00e9</b> \u2014 mais vous pouvez toujours regarder le classement en direct.',
        tutRace4: 'Le dernier joueur survivant est d\u00e9clar\u00e9 <b>vainqueur</b> !',
        tutTipsTitle: '\uD83D\uDCA1 Conseils et astuces',
        tutTips1: 'Restez toujours sur les <b>bords</b> de l\u2019\u00e9cran \u2014 les obstacles sont plus denses au centre.',
        tutTips2: 'En mode Ninja, faites de <b>longs balayages en diagonale</b> pour toucher plusieurs fruits \u00e0 la fois.',
        tutTips3: 'Collectez les <b>pi\u00e8ces t\u00f4t</b> en Infini \u2014 la vie suppl\u00e9mentaire est un excellent filet de s\u00e9curit\u00e9.',
        tutTips4: '\u00c9conomisez votre <b>XP</b> pour d\u00e9bloquer directement des niveaux \u00e9lev\u00e9s si D\u00e9butant est trop facile.',
        tutTips5: 'Les power-ups Ralenti vous laissent respirer \u2014 utilisez-les pour collecter les pi\u00e8ces sans danger.',
        tutTips6: 'Sur iPhone : appuyez sur <b>Partager \u2192 Ajouter \u00e0 l\u2019\u00e9cran d\u2019accueil</b> pour jouer hors ligne comme une vraie appli !',
        tutTips7: 'Partagez le lien <b>neon-dodgers.vercel.app</b> avec vos amis pour courir en ligne !',
        tutSurvivalTitle: '\u2764\uFE0F\u200D\uD83D\uDD25 Mode Survie',
        tutSurvival1: 'Vous avez exactement <b>1 Vie</b>. Un seul coup et c\u2019est fini \u2014 pas de vies suppl\u00e9mentaires, pas de piti\u00e9.',
        tutSurvival2: 'La vitesse <b>augmente sans cesse</b> \u2014 les obstacles ne cessent jamais d\u2019aller plus vite et d\u2019\u00eatre plus denses.',
        tutSurvival3: 'Votre score est un <b>chronom\u00e8tre</b> \u2014 chaque image survivue est un point. Battez votre meilleur temps !',
        tutSurvival4: '<b>Astuce :</b> les petits mouvements contr\u00f4l\u00e9s battent les mouvements fr\u00e9n\u00e9tiques. Rester calme sur les bords vous garde en vie le plus longtemps.',
        tutChaosTitle: '\uD83C\uDF0A\uFE0F Mode Chaos',
        tutChaos1: 'Les obstacles tombent <b>de toutes les directions</b> \u2014 haut, bas, gauche et droite. Surveillez tout l\u2019\u00e9cran !',
        tutChaos2: '<b>Les power-ups apparaissent bien plus souvent</b> \u2014 attrapez Ralenti ou Blaster d\u00e8s que possible.',
        tutChaos3: 'Vous commencez avec <b>3 Vies</b>. Les pi\u00e8ces donnent toujours +1 Vie chacune.',
        tutChaos4: '<b>Astuce :</b> en Chaos, le centre est un pi\u00e8ge. Campez dans un coin et r\u00e9agissez seulement quand quelque chose arrive vers vous.',
        tutSpeedRushTitle: '\u26A1 Mode Course de Vitesse',
        tutSpeedRush1: 'Vous avez <b>60 secondes</b> \u2014 le compte \u00e0 rebours s\u2019affiche l\u00e0 o\u00f9 se trouve normalement votre score.',
        tutSpeedRush2: '<b>Les pi\u00e8ces sont votre bou\u00e9e de sauvetage :</b> chacune ajoute +1 Vie ET +1 point. Attrapez-les toutes !',
        tutSpeedRush3: 'Quand le temps est \u00e9coul\u00e9, votre <b>score final est sauvegard\u00e9</b> comme votre meilleur. Battez-le au prochain essai !',
        tutSpeedRush4: '<b>Astuce :</b> restez en vie pendant les 60 s compl\u00e8tes. Mourir t\u00f4t g\u00e2che la partie \u2014 privil\u00e9giez l\u2019esquive plut\u00f4t que la chasse aux pi\u00e8ces.',
        tutMeteorTitle: '\u2604\uFE0F Mode M\u00e9t\u00e9ore',
        tutMeteor1: 'Un <b>marqueur d\u2019avertissement rouge clignotant</b> appara\u00eet avant qu\u2019un m\u00e9t\u00e9ore ne tombe \u2014 il montre exactement o\u00f9 l\u2019impact aura lieu.',
        tutMeteor2: 'Les m\u00e9t\u00e9ores <b>frappent depuis chaque bord</b> de l\u2019\u00e9cran, pas seulement le haut. Ne collez pas aux murs !',
        tutMeteor3: 'Apr\u00e8s l\u2019avertissement, le m\u00e9t\u00e9ore <b>s\u2019\u00e9crase et explose</b> en fragments. \u00c9vitez la zone d\u2019impact.',
        tutMeteor4: '<b>Astuce :</b> surveillez les avertissements, pas les m\u00e9t\u00e9ores. D\u00e8s qu\u2019un marqueur clignote, \u00e9loignez-vous.',
        tutReverseTitle: '\uD83D\uDD04 Mode Inverse',
        tutReverse1: 'Vos commandes sont <b>invers\u00e9es</b> \u2014 Fl\u00e8che droite vous d\u00e9place vers la GAUCHE, Fl\u00e8che haut vers le BAS. Souris/doigt invers\u00e9s aussi !',
        tutReverse2: 'Obstacles classiques d\u2019Infini, mais votre <b>cerveau doit fonctionner \u00e0 l\u2019envers</b> pour les esquiver.',
        tutReverse3: '<b>Astuce :</b> allez doucement au d\u00e9but. Bougez volontairement dans la "mauvaise" direction jusqu\u2019\u00e0 ce que l\u2019inversion devienne un r\u00e9flexe.',
        tutZenTitle: '\uD83E\uDDD8\u200D\u2642\uFE0F Mode Zen',
        tutZen1: '<b>Vous ne pouvez pas mourir.</b> Les obstacles vous traversent \u2014 pas de vies, pas de game over, pas de stress.',
        tutZen2: 'Chassez les <b>pi\u00e8ces</b> \u2014 chacune vaut +1 point. Votre objectif est un score \u00e9lev\u00e9 pur et relaxant.',
        tutZen3: 'Laissez-vous flotter dans le n\u00e9on. C\u2019est le mode parfait pour <b>vous d\u00e9tendre</b> et tester la boutique de skins.',
        tutZen4: '<b>Astuce :</b> pas de pr\u00e9cipitation ! Planifiez des chemins tranquilles \u00e0 travers les lignes de pi\u00e8ces et regardez les obstacles d\u00e9filer.',
        tutClose: '\u2705 Compris !',
        raceModeTitle: 'MODE COURSE', raceLastStanding: 'Le dernier survivant gagne !',
        racer1: 'NeonBot', racer2: 'CyberAce', racer3: 'PixelRush', racer4: 'Glitch',
        racer5: 'Vortex', racer6: 'StarDodge', racer7: 'Pulse'
      }
    },
    'fr-CA': {
      name: 'French (Canada)', nativeName: 'Fran\u00e7ais (Canada)', dir: 'ltr',
      s: {
        title: 'NEON DODGERS', score: 'Score', lives: 'Vies', best: 'Meilleur', keys: 'Cl\u00e9s',
        totalXp: 'XP Total', howToPlay: 'Comment jouer', language: 'Langue',
        retry: 'R\u00c9ESSAYER', mainMenu: 'MENU PRINCIPAL', gameOver: 'FIN DE PARTIE',
        youWin: 'VOUS AVEZ GAGN\u00c9 !', raceOver: 'COURSE TERMIN\u00c9E',
        diffBeginner: 'D\u00e9butant', diffEasy: 'Facile', diffNormal: 'Normal', diffHard: 'Difficile',
        diffExpert: 'Expert', diffMaster: 'Ma\u00eetre',
        raceTabCpu: 'contre CPU', raceTabOnline: 'En ligne',
        raceReady: 'Pr\u00eat', raceAgain: 'Refaire une course', raceMainMenu: 'Menu principal',
        tutClose: 'Compris !', scoreDisplay: 'Score\u00a0: {score}', livesDisplay: 'Vies\u00a0: {n}',
        keysDisplay: 'Cl\u00e9s\u00a0: {n}', bestDisplay: 'Meilleur\u00a0: {score}',
        xpDisplay: 'XP Total\u00a0: {xp}'
      }
    },
    'fr-CH': {
      name: 'French (Switzerland)', nativeName: 'Fran\u00e7ais (Suisse)', dir: 'ltr',
      s: {
        title: 'NEON DODGERS', score: 'Score', lives: 'Vies', best: 'Meilleur', keys: 'Cl\u00e9s',
        howToPlay: 'Comment jouer', language: 'Langue',
        retry: 'R\u00c9ESSAYER', mainMenu: 'MENU PRINCIPAL', gameOver: 'FIN DE PARTIE',
        youWin: 'VOUS AVEZ GAGN\u00c9 !',
        diffBeginner: 'D\u00e9butant', diffEasy: 'Facile', diffNormal: 'Normal',
        raceReady: 'Pr\u00eat', tutClose: 'Compris !',
        scoreDisplay: 'Score\u00a0: {score}', livesDisplay: 'Vies\u00a0: {n}',
        bestDisplay: 'Meilleur\u00a0: {score}', xpDisplay: 'XP Total\u00a0: {xp}'
      }
    },
    'fr-BE': {
      name: 'French (Belgium)', nativeName: 'Fran\u00e7ais (Belgique)', dir: 'ltr',
      s: {
        title: 'NEON DODGERS', score: 'Score', lives: 'Vies', best: 'Meilleur', keys: 'Cl\u00e9s',
        howToPlay: 'Comment jouer', language: 'Langue',
        retry: 'R\u00c9ESSAYER', mainMenu: 'MENU PRINCIPAL', gameOver: 'FIN DE PARTIE',
        youWin: 'VOUS AVEZ GAGN\u00c9 !',
        diffBeginner: 'D\u00e9butant', diffEasy: 'Facile', diffNormal: 'Normal',
        raceReady: 'Pr\u00eat', tutClose: 'Compris !',
        scoreDisplay: 'Score\u00a0: {score}', livesDisplay: 'Vies\u00a0: {n}'
      }
    },
    'fr-AF': {
      name: 'French (African)', nativeName: 'Fran\u00e7ais (Afrique)', dir: 'ltr',
      s: {
        title: 'NEON DODGERS', score: 'Score', lives: 'Vies', best: 'Meilleur', keys: 'Cl\u00e9s',
        howToPlay: 'Comment jouer', language: 'Langue',
        retry: 'R\u00c9ESSAYER', mainMenu: 'MENU PRINCIPAL', gameOver: 'FIN DE PARTIE',
        youWin: 'VOUS AVEZ GAGN\u00c9 !',
        raceReady: 'Pr\u00eat', tutClose: 'Compris !',
        scoreDisplay: 'Score\u00a0: {score}', livesDisplay: 'Vies\u00a0: {n}'
      }
    }
  };
  for (var k in S) { if (S.hasOwnProperty(k)) NeonI18n.addLang(k, S[k]); }
})();
